networks:
  directus_net:
    name: directus_net

services:
  db:
    image: postgres:15
    container_name: directus_db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: directus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U directus -d directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - directus_net

  directus:
    image: directus/directus:latest
    container_name: directus_app
    ports:
      - "8055:8055"
    restart: always
    build:
      context: ./directus
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./directus/extensions:/directus/extensions
    networks:
      - directus_net
    env_file: .env.local

  pgadmin:
    image: dpage/pgadmin4
    container_name: directus_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - directus_net

volumes:
  pgdata:
